# fly.toml app configuration file generated for minimessageboard888 on 2023-07-28T13:47:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "minimessageboard888"
primary_region = "ewr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
